//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DeployReport
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class rockEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new rockEntities object using the connection string found in the 'rockEntities' section of the application configuration file.
        /// </summary>
        public rockEntities() : base("name=rockEntities", "rockEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rockEntities object.
        /// </summary>
        public rockEntities(string connectionString) : base(connectionString, "rockEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rockEntities object.
        /// </summary>
        public rockEntities(EntityConnection connection) : base(connection, "rockEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rock_jmeter> rock_jmeter
        {
            get
            {
                if ((_rock_jmeter == null))
                {
                    _rock_jmeter = base.CreateObjectSet<rock_jmeter>("rock_jmeter");
                }
                return _rock_jmeter;
            }
        }
        private ObjectSet<rock_jmeter> _rock_jmeter;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rock_jmeter EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorock_jmeter(rock_jmeter rock_jmeter)
        {
            base.AddObject("rock_jmeter", rock_jmeter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rockModel", Name="rock_jmeter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rock_jmeter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rock_jmeter object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="recordTimeStamp">Initial value of the RecordTimeStamp property.</param>
        /// <param name="appName">Initial value of the AppName property.</param>
        public static rock_jmeter Createrock_jmeter(global::System.Int32 id, global::System.DateTimeOffset recordTimeStamp, global::System.String appName)
        {
            rock_jmeter rock_jmeter = new rock_jmeter();
            rock_jmeter.id = id;
            rock_jmeter.RecordTimeStamp = recordTimeStamp;
            rock_jmeter.AppName = appName;
            return rock_jmeter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset RecordTimeStamp
        {
            get
            {
                return _RecordTimeStamp;
            }
            set
            {
                OnRecordTimeStampChanging(value);
                ReportPropertyChanging("RecordTimeStamp");
                _RecordTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordTimeStamp");
                OnRecordTimeStampChanged();
            }
        }
        private global::System.DateTimeOffset _RecordTimeStamp;
        partial void OnRecordTimeStampChanging(global::System.DateTimeOffset value);
        partial void OnRecordTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssertionResult_Name
        {
            get
            {
                return _AssertionResult_Name;
            }
            set
            {
                OnAssertionResult_NameChanging(value);
                ReportPropertyChanging("AssertionResult_Name");
                _AssertionResult_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AssertionResult_Name");
                OnAssertionResult_NameChanged();
            }
        }
        private global::System.String _AssertionResult_Name;
        partial void OnAssertionResult_NameChanging(global::System.String value);
        partial void OnAssertionResult_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssertionResult_Failure
        {
            get
            {
                return _AssertionResult_Failure;
            }
            set
            {
                OnAssertionResult_FailureChanging(value);
                ReportPropertyChanging("AssertionResult_Failure");
                _AssertionResult_Failure = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AssertionResult_Failure");
                OnAssertionResult_FailureChanged();
            }
        }
        private global::System.String _AssertionResult_Failure;
        partial void OnAssertionResult_FailureChanging(global::System.String value);
        partial void OnAssertionResult_FailureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AssertionResult_Error
        {
            get
            {
                return _AssertionResult_Error;
            }
            set
            {
                OnAssertionResult_ErrorChanging(value);
                ReportPropertyChanging("AssertionResult_Error");
                _AssertionResult_Error = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AssertionResult_Error");
                OnAssertionResult_ErrorChanged();
            }
        }
        private global::System.String _AssertionResult_Error;
        partial void OnAssertionResult_ErrorChanging(global::System.String value);
        partial void OnAssertionResult_ErrorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResponseHeader
        {
            get
            {
                return _ResponseHeader;
            }
            set
            {
                OnResponseHeaderChanging(value);
                ReportPropertyChanging("ResponseHeader");
                _ResponseHeader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResponseHeader");
                OnResponseHeaderChanged();
            }
        }
        private global::System.String _ResponseHeader;
        partial void OnResponseHeaderChanging(global::System.String value);
        partial void OnResponseHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResponseData
        {
            get
            {
                return _ResponseData;
            }
            set
            {
                OnResponseDataChanging(value);
                ReportPropertyChanging("ResponseData");
                _ResponseData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResponseData");
                OnResponseDataChanged();
            }
        }
        private global::System.String _ResponseData;
        partial void OnResponseDataChanging(global::System.String value);
        partial void OnResponseDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RequestHeader
        {
            get
            {
                return _RequestHeader;
            }
            set
            {
                OnRequestHeaderChanging(value);
                ReportPropertyChanging("RequestHeader");
                _RequestHeader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RequestHeader");
                OnRequestHeaderChanged();
            }
        }
        private global::System.String _RequestHeader;
        partial void OnRequestHeaderChanging(global::System.String value);
        partial void OnRequestHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QueryString
        {
            get
            {
                return _QueryString;
            }
            set
            {
                OnQueryStringChanging(value);
                ReportPropertyChanging("QueryString");
                _QueryString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QueryString");
                OnQueryStringChanged();
            }
        }
        private global::System.String _QueryString;
        partial void OnQueryStringChanging(global::System.String value);
        partial void OnQueryStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ResponseTime
        {
            get
            {
                return _ResponseTime;
            }
            set
            {
                OnResponseTimeChanging(value);
                ReportPropertyChanging("ResponseTime");
                _ResponseTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResponseTime");
                OnResponseTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _ResponseTime;
        partial void OnResponseTimeChanging(Nullable<global::System.Int32> value);
        partial void OnResponseTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CGIName
        {
            get
            {
                return _CGIName;
            }
            set
            {
                OnCGINameChanging(value);
                ReportPropertyChanging("CGIName");
                _CGIName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CGIName");
                OnCGINameChanged();
            }
        }
        private global::System.String _CGIName;
        partial void OnCGINameChanging(global::System.String value);
        partial void OnCGINameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReturnCode
        {
            get
            {
                return _ReturnCode;
            }
            set
            {
                OnReturnCodeChanging(value);
                ReportPropertyChanging("ReturnCode");
                _ReturnCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReturnCode");
                OnReturnCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _ReturnCode;
        partial void OnReturnCodeChanging(Nullable<global::System.Int32> value);
        partial void OnReturnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cookies
        {
            get
            {
                return _Cookies;
            }
            set
            {
                OnCookiesChanging(value);
                ReportPropertyChanging("Cookies");
                _Cookies = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cookies");
                OnCookiesChanged();
            }
        }
        private global::System.String _Cookies;
        partial void OnCookiesChanging(global::System.String value);
        partial void OnCookiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Method
        {
            get
            {
                return _Method;
            }
            set
            {
                OnMethodChanging(value);
                ReportPropertyChanging("Method");
                _Method = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Method");
                OnMethodChanged();
            }
        }
        private global::System.String _Method;
        partial void OnMethodChanging(global::System.String value);
        partial void OnMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TestMachineIP
        {
            get
            {
                return _TestMachineIP;
            }
            set
            {
                OnTestMachineIPChanging(value);
                ReportPropertyChanging("TestMachineIP");
                _TestMachineIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TestMachineIP");
                OnTestMachineIPChanged();
            }
        }
        private global::System.String _TestMachineIP;
        partial void OnTestMachineIPChanging(global::System.String value);
        partial void OnTestMachineIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThreadName
        {
            get
            {
                return _ThreadName;
            }
            set
            {
                OnThreadNameChanging(value);
                ReportPropertyChanging("ThreadName");
                _ThreadName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThreadName");
                OnThreadNameChanged();
            }
        }
        private global::System.String _ThreadName;
        partial void OnThreadNameChanging(global::System.String value);
        partial void OnThreadNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentCGIName
        {
            get
            {
                return _ParentCGIName;
            }
            set
            {
                OnParentCGINameChanging(value);
                ReportPropertyChanging("ParentCGIName");
                _ParentCGIName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ParentCGIName");
                OnParentCGINameChanged();
            }
        }
        private global::System.String _ParentCGIName;
        partial void OnParentCGINameChanging(global::System.String value);
        partial void OnParentCGINameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AppName
        {
            get
            {
                return _AppName;
            }
            set
            {
                OnAppNameChanging(value);
                ReportPropertyChanging("AppName");
                _AppName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AppName");
                OnAppNameChanged();
            }
        }
        private global::System.String _AppName;
        partial void OnAppNameChanging(global::System.String value);
        partial void OnAppNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SeqNum
        {
            get
            {
                return _SeqNum;
            }
            set
            {
                OnSeqNumChanging(value);
                ReportPropertyChanging("SeqNum");
                _SeqNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SeqNum");
                OnSeqNumChanged();
            }
        }
        private global::System.String _SeqNum;
        partial void OnSeqNumChanging(global::System.String value);
        partial void OnSeqNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JmxFileName
        {
            get
            {
                return _JmxFileName;
            }
            set
            {
                OnJmxFileNameChanging(value);
                ReportPropertyChanging("JmxFileName");
                _JmxFileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JmxFileName");
                OnJmxFileNameChanged();
            }
        }
        private global::System.String _JmxFileName;
        partial void OnJmxFileNameChanging(global::System.String value);
        partial void OnJmxFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String exeUser
        {
            get
            {
                return _exeUser;
            }
            set
            {
                OnexeUserChanging(value);
                ReportPropertyChanging("exeUser");
                _exeUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("exeUser");
                OnexeUserChanged();
            }
        }
        private global::System.String _exeUser;
        partial void OnexeUserChanging(global::System.String value);
        partial void OnexeUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numInSameSeq
        {
            get
            {
                return _numInSameSeq;
            }
            set
            {
                OnnumInSameSeqChanging(value);
                ReportPropertyChanging("numInSameSeq");
                _numInSameSeq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numInSameSeq");
                OnnumInSameSeqChanged();
            }
        }
        private Nullable<global::System.Int32> _numInSameSeq;
        partial void OnnumInSameSeqChanging(Nullable<global::System.Int32> value);
        partial void OnnumInSameSeqChanged();

        #endregion

    
    }

    #endregion

    
}
